### ISSUE TITLE
Sent status alway sent and never delivered in group chat

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#1188]
In group chat, I always see that my messages are with status "sent" and never "delivered".
I expected, that as soon as all recipient get it, the message would turn to "delivered".
Is that correct ?

**Comment by Awerick** [comment]
If I remember correctly, the status should already change to "delivered" as soon as _one_ recipient got the message.
But there seems to be a bug that was introduced 2 or 3 months ago...
(Cross-issue in the android repository: wireapp/wire-android#943.)

**Comment by typfel** [comment]
Delivery recipes are not sent in group chats for performance reasons.

**Comment by Awerick** [comment]
Delivery recipes have a notable performance impact?
Can you tell us whether this is only a temporary restriction – so, delivery recipes will be reintroduced if the performance problems are fixed?

(I remember that a few months ago, delivery recipes were actually sent in group chats.)

**Comment by typfel** [comment]
The problem with delivery recipes is that if you send a message in a group chat every other client in that chat will respond to you forcing you to potentially decrypt 1024 messages (128 participants x 8 clients ).  Potentially we might enable them in future if we find a technical solution for this or we re-define what delivery recipes mean in group chats.

**Comment by Awerick** [comment]
Ah, thanks for the explanation! :+1:

However when I think about it now, I don't see a big problem:
Of course decrypting 1024 delivery recipes is a huge number – but when you sent the message, you also had to encrypt it 1024 times!

=> So it does not seem like a polynomial/exponential overhead for groups, but natural scaling:
"Implementing delivery recipes increases the communication (en-&decryption operations) by a factor of 2."
_(Assuming that the delivery recipes are only sent to the original sender, not all participants.)_

If this "factor of 2" is no performance problem in one-to-one conversations (as Wire has delivery recipes for these), I don't see it as a problem for group chats…

**Comment by Awerick** [comment]
Hm (to be self-critical): My considerations above might lack the user experience aspect:
Even though the number of en-&decryption operations are the same, they might affect the user's perspective differently due to the different situations they occur in:
 *  The user might be ok/understand, that _sending_ a message in a big group takes some time (encrypting it 1024 times).
 *  However the user might NOT be ok, that (_after_ the message is sent) the app reacts slower over some time due to the incoming (1024) delivery recipes.
    _(But is the slow-down really noticeable with our advanced hardware?)_

(Also: My "factor of 2" only considers the one client, the sender used to send & encrypt the message.
The sender can potentially have 7 additional clients, that did not send the message, but which will also receive the delivery recipes… – However this is again no difference to one-to-one conversations.)

* * * * *

_Just an idea for reducing the number of delivery recipes for the original sender (optimally: ⅛) that I want to share:_

Only the first client that receives a message, sends the delivery recipe. To prevent the other 7 clients from sending the delivery recipes, it sends the delivery recipe to them as well (I think this is actually the same procedure as sending normal messages…). Implementing this might be tricky, as all clients have to check for these "internal" delivery recipes before sending a delivery recipe on their own.

However the benefit may vanish, if several clients are online at the same time: The clients may send a delivery recipe before they receive the "internal" delivery recipes of the other clients.
But in general it should reduce the total number of delivery recipes that the sender will get. (I suppose, that typically not all clients are online at the same time.)

_This would even improve privacy (also for one-to-one conversations):_ The original sender only gets to know, when the first client of each participant receives the message – not when each of the clients received the message/went online.
