### ISSUE TITLE
No Notification Badge (red-dot) for New Messages

### ISSUE THREAD

**Issue by MirrorDM** [wireapp/wire-ios#1338]
When receive new messages, notification works. But the app does not display the red-dot on the 'wire' icon.

Have checked the setting of notification, the Badge App Icon is on.

Device: iPhone 7
System: IOS 10.3.3
Version: 2.43(2895)

**Comment by VaHiAtlanta** [comment]
Same issue. Since the last update, I am no longer getting the red badge counter on the Wire app icon to let me know a message has arrived.  I have to manually pull down notifications from the top to look for a prior banner notification to see if there’s s message or actually log into the app.  Reported it to customer support and got email back saying they are aware of the problem. Hope it gets fixed soon. I really like Wire but it is not as useful if I don’t know when messages arrive.

**Comment by KoalaBoomka** [comment]
Hi, @MirrorDM, @VaHiAtlanta!

Thanks for getting in touch with us. Next release will have this issue fixed.

**Comment by mikeger** [comment]
Should be fixed with this change: https://github.com/wireapp/wire-ios-sync-engine/pull/582

**Comment by mikeger** [comment]
@VaHiAtlanta @MirrorDM please try Wire 3.0 from the App Store, it should have the fix.

**Comment by MirrorDM** [comment]
Hi, @mikeger 
I have tried the Wire 3.0, the badge is back! Thank you!!

**Comment by VaHiAtlanta** [comment]
Working for me too. Thank you!
