### ISSUE TITLE
I can't find these audio files in the project package

### ISSUE THREAD

**Issue by 353243186** [wireapp/wire-ios#1555]
Dear supporters,
When I choose the ring in simulator,The app crashed
<img width="436" alt="wx20171222-165851 2x" src="https://user-images.githubusercontent.com/13417472/34292211-e261aa7e-e73a-11e7-9ab3-08845ecf3f83.png">
Then I checked the project,
 I can't find these audio files in the project package
<img width="623" alt="wx20171222-165654 2x" src="https://user-images.githubusercontent.com/13417472/34292390-ad725592-e73b-11e7-91f1-6b2f01f108f2.png">

**Comment by mikeger** [comment]
Hey @353243186 ! Thanks for reaching out to us. The sound files for technical reasons have to be copied into the root of the application bundle, however we cannot put them into the GPL repository since they are not produced by us. In order to make this feature work you would have to copy the same named files into the application bundle, i.e. `tri-tone.m4a` and others.

**Comment by 353243186** [comment]
thanks!
