### ISSUE TITLE
Unable to log in via app

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-ios#1748]
## The problem

If user already has an account, they are unable to log in via a freshly installed app.

## Details
After selecting [phone] on the first screen and typing in the phone number, the screen moves to a different step of the process. Sometimes I can see the field to enter the 6digit code for a couple of seconds, sometimes I don't see it at all. In any case, when the SMS arrives 10 seconds later, it's always too late and screen has already moved to "Add your email and password." Please note there is no visible way to go back to previous screen from there and actually finish logging in. I also can't seem to find a "skip" button. Maybe it's hidden behind the keyboard?

**Comment by 0ki** [comment]
This change is undocumented AFAIK and not clear at all.
Also, how does the user opt out? You can't just expect the user to go register an e-mail address, if they don't have one. Or even worse, why would a privacy focused company force this type of "consent" on their user?

Finally, how does this align with GDPR? The user can't even decide to kill their account, if they feel uncomfortable with the change.

**Comment by 0ki** [comment]
I spent 15 minutes debugging this for a user, not even being able to image that Wire would make a move like this.

**Comment by kristin-wire** [comment]
Hi @0ki,

Sounds frustrating! Mind if I ask a couple follow-up questions to better understand what happened, and ultimately debug faster?

1. Did you log out or were you force logged out by the app at any point?
2. Is the device you're trying to login on the original device you registered for Wire on?
3. If yes to 2, did you ever uninstall and reinstall the app?

**Comment by 0ki** [comment]
1. No. The user got a new device.
2. No.

**Comment by 0ki** [comment]
Any updates on this? Not that it matters, I think the user has abandoned wire being unable to log in for more than 2 weeks.

**Comment by mikeger** [comment]
Hey, we are working on this, release 3.9 must have a proper fix.

Sent from a Mobile Device

**Comment by 0ki** [comment]
Thanks.

**Comment by 0ki** [comment]
The ux for this case has indeed been improved.
Now it's absolutely clear to the user that his account is being held ransom until certain demands are met, namely, user registers and provides an e-mail address to wire.
I would strongly caution against such behaviour as some users might be inclined to use a throwaway open address like @malinator. 

In any case user needs the option on that screen to "revoke access to all other devices; this is my only device" when they want to setup the new device as their sole device. Or at the very least to comply with GDPR, a button saying "screw this noise, kill my account".

Thanks!

**Comment by mikeger** [comment]
Hey @0ki, you can ask customer support to delete your account if you wish to. The original issue where user is unable to enter the sign in code is fixed, so I am closing this one. Requirement to add the email if you are signing in with the phone number is only intended to make one’s account more secure, since by many reports (see https://www.google.de/amp/s/amp.ft.com/content/74d5ce00-12dd-11e6-839f-2922947098f0 ) show that the pure phone sign in is not safe enough.

**Comment by 0ki** [comment]
Please provide a web form or a phone number that a person without an e-mail account can reach out to to get their account deleted.

**Comment by mikeger** [comment]
Hey, I think it should work via https://support.wire.com/hc/en-us/requests/new . If it does not, we can also set you in direct connection with CS.

**Comment by 0ki** [comment]
It doesn't work. Requires an e-mail address. http://02.lv/f/2018/08/09/doesntwork.png

It's not my account. It's my friends. I think it's a travesty against users who do not have an e-mail address to lock them out of their accounts and not even provide a way to close their account in a streamlined fashion. "delete" button absolutely has to be added to the UI.

**Comment by kristin-wire** [comment]
Hey @0ki 

To close an account, we need to verify the user's identity. For this reason, we ask your friend to log in to their own account **with their phone number,**** and close it on their own. Here's how:

[Mobile:](https://support.wire.com/hc/en-us/articles/207504725-How-can-I-delete-my-Wire-account-) How can I delete my Wire account?
[Desktop](https://support.wire.com/hc/en-us/articles/207555795-How-can-I-delete-my-Wire-account-): How can I delete my Wire account?

If your friend is prompted to add an email address, it is because s/he has delete/reinstalled the app, or is logging in on another device. In this case, Wire requires users to add an email as a security feature-- should one of your devices become compromised. We notify users each time there is a new login via email, and they they can protect their own account.

This email of course can be a throw away email, which will be deleted as soon as the account is deleted. Your friend does not need to re/download Wire - s/he can log in on desktop in a browser at app.wire.com.

If your friend still is having troubles deleting their account we at Support are of course here to help. You can contact us via https://support.wire.com/hc/en-us/requests/new/. Submitting a ticket though, you will need to provide an email, so that we can actually correspond with you, in order to verify the identity of the owner of the account before deleting it.

Hope this helps to clarify.
