### ISSUE TITLE
Better Inter-App Communication

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#203]
It would be interresting to reach a better Inter-App Communication with other iOS applications.

For exemple, a media could be shared /open with another application:

Exemple: 
- I receive a picture and want to save it to BTsync / DropBox / ...
- I receive a link and want to open it with Firefox / Brave / Pocket / Instapaper

**Comment by david-wire** [comment]
Thanks for the suggestion, nothing planned regarding this though.

**Comment by jenskasemets** [comment]
Option to choose different external applications for the links in the conversation was added in release 2.21

**Comment by IpsmLorem** [comment]
Still need to implement choosing for medias

**Comment by MadEgg** [comment]
I'm running 2.22 but I don't see anything like what @IpsmLorem describes? Where can I choose how to open links? I also don't get a share option for any media received.

**Comment by jenskasemets** [comment]
@MadEgg If you go to Wire settings, and choose Advanced (this location will change in next release), under that you see "Open links in". Currently you can define apps for tweets, maps and browser. Because there's no system wide possibility to know which all apps are available for such link types, we needed to pre-define list of supported apps, thus limited selection, just most popular apps.

**Comment by jenskasemets** [comment]
@IpsmLorem you are correct, we had that possibility, but with limited functionality, need to re-introduce while doing share extension

**Comment by MadEgg** [comment]
Isn't there an actual share extension for this in iOS? In most apps when I view an image, video or document, I get a rectangular button with an arrow in the corner and if I click that, I can send it off to any application that is registered as accepting that type of content, including obscure apps the builder of the app probably had know idea I would have installed. Unfortunately, Wire is missing from this list in other apps, but I guess that's related to #273 This seems to be facilitated by iOS, rather than the developer of the app I'm using.

I don't see any way to change 'Open links in', under settings -> Advanced, by the way. The complete list I see is:

'Usage and Crash Reports'
'Calling Debug Report
'Reset Push Notifications Token'
'Version Technical Details'

Settings->About tells me I'm running Version 2.22 (2713).

**Comment by jenskasemets** [comment]
@MadEgg If you don't see that section under settings, it means you don't have any of the apps installed that have been defined by Wire, here you can find exact list:
https://github.com/wireapp/wire-ios/blob/develop/Wire-iOS/Resources/Base.lproj/Localizable.strings#L496-L511

To have Wire in the list of apps in the share dialog from other apps requires implementation of share extension (requested and commented reasons why it's not so trivial in our case in #273). To share content from Wire to other apps is way easier, but currently not implemented and not in the near time plans. We'll keep this request in mind and will let you know when it will be there.

**Comment by marcoconti83** [comment]
The share extension to share from other apps into Wire has been implemented quite some time ago. Apologies for not updating this ticket earlier. Closing it now.
