### ISSUE TITLE
Storage security by design

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#210]
Data at rest must be secured by design.

All file data must have an explicit "NSFileProtectionComplete" attribute and each secrets (acess token, user token, identity private key "a" and private prekeys "k(a,i)"), must be stored in the iOS Keychain with attribute "WhenPasscodeSetThisDeviceOnly".

Furthermore, all file data must be properly encrypted by wire app with a key derived from user password. This key is either not persistent (which imply asking for user password each time the application is wiped from memory) or stored in the keychain with "WhenPasscodeSetThisDeviceOnly" attribute and proper ACL (authenticated using Touch ID (by entering the device’s passcode maybe unfriendly) or tripin (3 states PIN number, color/number/geometric form) within Wire. For touch ID: Acess limited by specifying that
Touch ID enrollment has not changed since the item was added.)

Those measures prevent data leak from iTunes backup and iOS sandbox breach and more.

**Comment by raphaelrobert** [comment]
Thanks for the input, here are some details:

We experimented with using “NSFileProtectionComplete” but this prevented us from accessing the database and the key material when we receive a push notification from Apple. Since the content is end-to-end encrypted, our backend can not access the content of a message so the push notification will only contain encrypted data, and access to the database and the key material is needed to decrypt the payload in order to display meaningful text to the user in the notification. In other words, “NSFileProtectionComplete” will make it impossible to have content in push notifications.
For this reason we set on using instead “NSFileProtectionCompleteUntilFirstUserAuthentication” to allow the user to receive push notifications as soon as it unlocked the device once.
The key material is stored on disk, backup is disabled on that folder, and it is also under “NSFileProtectionCompleteUntilFirstUserAuthentication” as the original implementation of Cryptobox did not support external storage (e.g. keychain) for key material. This is now available as an option and we might consider moving the material to the keychain, but we need to evaluate the implications (storing on disk has the advantage that uninstalling the app also deletes the keys, while they will remain in the keychain if they are stored there).

Encrypting local data with a user password typically has one of two problems: Either it is short and convenient to enter (and therefore insecure), or it is long enough but a hassle to enter. In our case, not every user has a password btw, only if they signed up with an email address.

Furthermore sensitive data is not included in iTunes/iCloud backups, so there is no need to protect it with yet another layer of encryption.

Regarding the screen lock: this is something we are considering.

**Comment by IpsmLorem** [comment]
What about a first run generated key, stored in the keychain, used only for local storage encryption ?
No password derived at all and can be used by Wire app without further user interaction.
By the way, this could open the option to provide to user a stronger ACL, if desired.

Furthermore, it will enhance forensinc leakage prevention.

All Cryptobox secrets may be still stored on file system, encrypted by this keychain-first-run-generated key. When wire will be deleted, the file system will de deleted (an so Wire transmission key materials) and only the storage encryption key could remain in the keychain.
If the user reinstall, the storage encryption will be rewritten in the keychain.

**Comment by raphaelrobert** [comment]
It's not clear what problem your suggestions are supposed to solve.
As mentioned before, sensitive data like key material and messages are not in the iTunes/iCloud backups anyway. Therefore the only way to do a forensic analysis would be to jailbreak an iOS device, at which point all bets are off anyway.
Regardless of the above, the problem remains that the keychain is not accessible when the device is locked and therefore the decryption key cannot be used.

**Comment by IpsmLorem** [comment]
Sorry I'm not clear enough and I really want to try to help improving Wire.

My goal is to prevent Apple FS encryption bypass (software/hardware vulnerability), by adding a second defense application layer, relaying on the >A7 secure enclave via keychain. 

I though that the keychain was accessible while locked with the kSecAttrAccessibleAfterFirstUnlock attribute ?

**Comment by raphaelrobert** [comment]
Well yes, but what good is a key stored on the same system next to the cipher text?

If you want to discuss ideas, you are welcome to send a ticket to [Wire support](https://support.wire.com/hc/en-us/requests/new) and we can take it from there.

**Comment by IpsmLorem** [comment]
:+1:
