### ISSUE TITLE
Taking CoreData operations off main thread

### ISSUE THREAD

**Issue by saraseif** [wireapp/wire-ios#2215]
Hello guys!

According to best practices, it is better to do Coredata related operations in the background, not to cause any possible performance drops, or UI blocks.

I feel like you are doing some database access in the main thread:

1. Class: DraftsRootViewController, function:viewWillAppear, 
2. Class: MessageComposeViewController, function: updateLeftNavigationItem,
are both calling numberOfStoredDrafts which is doing database operations.

Don't you think it would be better to take these operations off the main thread?

**Comment by mikeger** [comment]
Hey @saraseif ! Thanks for the suggestion, generally the advise that you are giving is good and valuable, however I think as any other advice has the cases when it can be applied, since it has it's pros and cons. Let me explain it in detail.

So the approach with accessing the database from the main thread has the following cons, as you mentioned:

- The access is blocking, which means that potentially the app can be "stuck" doing the database query. This can potentially make the application UI appear less performant.

However, it has the following pros:

- Accessing the database from the main thread is ensuring the query result is delivered right after the query, so developer does not have to think about synchronizing the result appearance and the view updates.
- The view is always updated with the data when it is displayed, so no need to insert the loading spinners.
- The code written in that way is more robust and easy to understand.

In the cases that you highlighted, the performance of the database queries is not important, since it is only concerning the drafts feature, and user cannot have too many drafts.

In the other parts of the application (see https://github.com/wireapp/wire-ios-data-model ) we are using the second background managed object context to perform the batch changes and updates on the database, also we are doing the message search on the background. Those performance-intensive operations are worth putting on the background thread, as you underlined, for making the app more responsive and fast.

I hope this is answering your question.

**Comment by saraseif** [comment]
Hello @mikeger !

Thank you for your time and your thorough response. 
I am working on a static checker to find out this sort of anti-pattern (heavy work on UI). Running this tool on your app showed me the mentioned 2 cases only, so yeah! I see you use background managed object context for many heavy database acts :) 
In general, how useful do you find such tool? Showing warnings about this anti-pattern as you go, to keep your attention on this, so that if you think the operation is heavy, you consider taking it off main thread?

**Comment by mikeger** [comment]
@saraseif it would be interesting to try such a tool. Can it handle both Swift and Objective-C?

**Comment by saraseif** [comment]
@mikeger for now it only handles Swift

**Comment by mikeger** [comment]
This should be fine for now, since we only write the new code in Swift.
