### ISSUE TITLE
can't open conversation with contact after content deleted

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-ios#2428]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Tapping on a contact simply redirects back to the existing conversations and does not add a new conversation for the contact.

## Environment

* Wire version that exhibits the issue: 3.17
* Last Wire version that did not exhibit the issue (if applicable): this bug has existed for years.
* iOS version used to run Wire: 10.3.3
* iOS device type: iPhone 6s
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi

## Details

My  environment is this: 

Wire is running on macOS on a desktop
Wire is running on an iPhone 6s on iOS 10.3.3 

If I delete all content with a contact on the desktop, it correctly deletes on the iPhone. However, it's not possible to start a new conversation with a contact on the iPhone. It's possible to do this on the desktop in which case it will open on the phone too.

I never had a version of wire where this was not a problem.

In the past it used to be possible to force open a conversation by selecting a contact and sending an image to them. That however doesn't seem to be an option now, so once the content is cleared on the desktop it is sayonara forever to being able to talk to that person until you can get back to the desktop.

I've worked around this by emailing the contact and telling them to send me a message, which opens up the conversation again.

I think I reported this before, years ago.

**Comment by mikeger** [comment]
Hey @dbquarrel ! Thanks for reposting the issue that you've experienced. Just to clarify: when you are deleting the conversation content and opening the conversation again it's not creating the new conversation for you, it's reusing the one where the content was erased. Generally speaking, you can have only one 1-1 conversation with user. Optionally you can create the group conversation with only you and the user who you want to talk to, but then it would be logically different type of the conversation, since there you would be able to add other participants.

I am trying to reproduce with the following steps:
1. Log in to desktop and iOS with the same account.
2. On desktop delete the conversation content with some other participant.

For me I still see the conversation on iOS in the list without the content. May be I misunderstood the steps from your post, or you had some extra things done that I am missing? Thanks in advance.
