### ISSUE TITLE
Question：Why iOS logout need to erase chat history?

### ISSUE THREAD

**Issue by crystalztl** [wireapp/wire-ios#2489]
Why iOS logout need to erase chat history while android does not? any reason beneath?

**Comment by mikeger** [comment]
@crystalztl we prefer to erase the chat history because if we don't, then the user account's data would persist on the device in the way that user would not be able to see it, whereas if hacked, this data can potentially leak. The ideal way is to give user the choice to keep the data, and show the list of not logged in accounts in settings, but we don't have it currently on our recent timeline.

**Comment by crystalztl** [comment]
@mikeger Thanks for reply. May I know why in android platform it does not erase chat history and user would be able to see the data?

**Comment by mikeger** [comment]
Hey, the implementation details on different platforms may vary because of the workload or the technical details of the platforms. We are trying to minimize the differences if possible.
