### ISSUE TITLE
Develop branch crashing on launch

### ISSUE THREAD

**Issue by KVTaniguchi** [wireapp/wire-ios#268]
After pulling down the latest develop branch and running the set up script, I can't get the app the properly launch in the simulator.  

It seems to crash some where in the ```AppController``` ```- (void)loadUserSession method.```
[2016/10/04 19:37:49:004] (INFO ) AVS: flowmgr(0x7fa92e0eaf48): alloc: (avs 2.8.65 (x86_64/darwin))
 (AVSLogObserver:47)

**Comment by mikeger** [comment]
Hey @KVTaniguchi ! The issue is with iOS 10 simulator, it cannot handle the capture sessions any more. Please go to simulator's settings where you see Wire-specific configuration and toggle "Disable AVS" ON: 
![screen shot 2016-10-05 at 10 54 18](https://cloud.githubusercontent.com/assets/715129/19106940/1e4232c4-8aea-11e6-909e-61eb9f1db025.png)

We have a proper fix for it, I would try to propagate it to `develop`.

**Comment by mikeger** [comment]
You can also test on device temporarily, there you have no issues with capture session.

**Comment by mikeger** [comment]
@KVTaniguchi please check against current `develop`: https://github.com/wireapp/wire-ios/commit/e181bac0d251bda1619be03af90793c869cc49db

**Comment by KVTaniguchi** [comment]
@mikeger I get ```The app ID "com.wearezeta.zclient-alpha" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.``` when I try to run on device, changing the AVS settings in the sim does work, the latest dev does not after running setup - I can work off the AVS settings change though.  Much thanks!
