### ISSUE TITLE
Add Wire to system share extension

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-ios#273]
Would be useful to be able to use the share extension (ex: from photos or Safari) to hop directly into Wire and share content

**Comment by mikeger** [comment]
Hey @notagithubuser ! Thanks for the suggestion. Sounds good, and we are actually looking into it. We used to have the share extension before we introduced the E2EE. Right now it is quite tricky to do, since the share extension is running into different process and we would have to share the key information between two processes, but we have it on our backlog.

**Comment by IpsmLorem** [comment]
Related to #203

**Comment by MadEgg** [comment]
On behalf of several of my less tech-savvy contacts on Wire I'd like to promote this issue, too ;-) They find it too hard to share photos using Wire - not when it's pictures they took themselves on their own phone (these show within Wire directly), but when they received them by other means. For example when receiving a picture by e-mail. Right now, you can't tap the picture in the e-mail and select Share using Wire. You can select Share using WhatsApp or Telegram, for example. Now, they have to save the image from the e-mail app first, before they can select it in Wire for sharing (and there seems to be some delay there before it actually shows up in Wire occasionally, too).

**Comment by marcoconti83** [comment]
Thanks all the feedback. 
We are currently working on this feature and will update this tickets once we have our first public release with the share feature!

**Comment by 0ki** [comment]
Just a a workaround - Wire supports copy and paste on iOS perfectly. I personally prefer that way more.

**Comment by MadEgg** [comment]
Thanks for the suggestion - that indeed works nicely. Didn't know that that could be used for images. However, it's a work around, I hardly expect my contacts to know of this functionality - they are now constantly reverting to WhatsApp because they have problems sharing pictures using Wire. 

They also miss the function to share multiple pictures at once, and to add captions to images. It seems WhatsApp has set some standards that need to be conquered before my promotional campaign of Wire can be truly effective :(

**Comment by jenskasemets** [comment]
Share extension is now available in version 2.28
