### ISSUE TITLE
Wire App in IOS

### ISSUE THREAD

**Issue by mallikarjunareddy94** [wireapp/wire-ios#2751]
How to Integrate the Wire App in IOS using cocoa pods or Garthage

**Comment by mikeger** [comment]
Hey, can you elaborate what is the aim, i.e. what would you like to receive as the end result?

**Comment by mallikarjunareddy94** [comment]
Hi,
I would like add wire App feature in my project(IOS). Would please suggest me, how to integrate the WireApp in IOS. As I am not getting, which you presented in Github.

Thanks & Regards
Mallikarjun

**Comment by mikeger** [comment]
So just a heads-up, Wire-iOS project is licensed under GPL, therefore if you are going to integrate it into your project you would have to license your project under GPL (and make it open-source).

Otherwise Wire-iOS is currently shipped as the standalone app, I am not sure what is the best way to integrate it into another app. We have no experience with it at the moment of time. Looks like you would have to do it yourself.

**Comment by mallikarjunareddy94** [comment]
Can you connect this, to the Technical Support Team. So, It will be so helpful for me or else can you arrange me a call regarding this concert

Thanks 
Mallikarjun

**Comment by mikeger** [comment]
@makingthematrix you can reach wire support here https://support.wire.com/hc/en-us

**Comment by mikeger** [comment]
I am going to close this one for the moment. Feel free to reopen if you have any further questions.
