### ISSUE TITLE
Send button in the Giphy doesn't work

### ISSUE THREAD

**Issue by AndreaVEH** [wireapp/wire-ios#317]
In the latest iOS Wire app, clicking on the send button doesn't have any response in the Giphy. But cancel button nexting to it works.

**Comment by KoalaBoomka** [comment]
hi, @AndreaVEH!
Thanks for contacting us. Send button works for me on AppStore build 2.18.2669.
Could you, please, provide more details: 
* What are your steps for getting there? 
* What are the phone model and iOS version you using?

**Comment by AndreaVEH** [comment]
- In the conversation, tap GIF on the toolbar, and choose one of the GIFs, then tap on the send button and nothing happens, but tapping on cancel makes me back to the Giphy choosing view.
- iPhone SE iOS 10.0.2
- Wi-Fi
- Having tried to restart the iPhone, but problem still exists.

**Comment by KoalaBoomka** [comment]
Thanks for the details, @AndreaVEH!
We'll investigate and prioritize this issue.

**Comment by AndreaVEH** [comment]
Hi, @KoalaBoomka. I find there are two kinds of send button. One is light color, the other is dim one. Send button with light color works, but the other doesn't. Does the GIF need to download again after entering the send screen before it can be sent? If yes, it seems it's my network problem, not a bug.

**Comment by KoalaBoomka** [comment]
@AndreaVEH, when you see the grid of the gifs, these are previews in a low resolution. When you select a gif for sending, the app downloads the full resolution image. In your case, it's quite possible that Internet connection was no so good and it took some time for downloading it, that's why Send button was in inactive state. 
Thanks for pointing out on this case.

**Comment by AndreaVEH** [comment]
@KoalaBoomka You are welcome.
