### ISSUE TITLE
Auto-negotiate redelivery of failed messages

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#358]
More than once I now ran into the situation where some messages are received on another device (the Wire desktop app), but not on my iPhone. It says 'A messages from <someone> was not received. Why?'. I understand this has something to do with it not being able to decrypt the message.

However, my chat-partner has no way of knowing this and I have no way of requesting a re-transmission. Also, my other device, the desktop app does have the message.

I think this process can be streamlined to make it more user-friendly. I don't know what the exact cause of the failure is, but the device could report the failure to the chat-partner's device and request a re-transmission. Possibly preceded by a session reset. Alternatively, it could request transfer of the message from one of the other devices so that when at least one device received the message, the others can get it from there. But I'm thinking that that may have some negative consequences on integrity validation, so automated requesting re-transmission from the original chat-partner would probably be the safest method.

**Comment by raphaelrobert** [comment]
What you describe can of course happen sometimes. It has to do with the fact that messages are individually encrypted between devices, and sometimes this encryption fails.
We decided not to implement any automatic re-transmission between clients, because such a mechanism can easily be abused. It would mean that a client can request part of the history from another client without any user action to approve it and that could be dangerous.
Therefore the best way right now is to manually request a re-transmission (on the human level).
On another note we recently experienced some problems with the web app/desktop apps regarding encryption. If these things happen feel free to post it on GitHub or with customer support (https://support.wire.com). It helps us to improve things!

**Comment by MadEgg** [comment]
I can understand your reasons for not wanting to implement this, at least not automatically. But wouldn't a button to request re-transmission be an option then? So that when I get the message that decryption failed, I can manually request it and my chat partner gets the request in the chat and has to approve it manually.

However, such a solution is also not necessary if doesn't happen frequently. But I've experienced it twice over the past week, with the same chat partner. My devices: iPhone, Web App session in Firefox and the Linux Wire Desktop app. Chat partner's devices: iPhone and iPad. In both cases, the message was correctly delivered on one of my devices but not on the others. Usually, it was received correctly on the device I used  most recently before the failed messages were sent.

You say I should report these issues: sure, I'll be glad to do so. However, I can imagine that the information I'm providing here isn't sufficient to localize the problem, so could you give me some guidelines as what information I can provide to make it easier to locate and fix these issues? Thanks!

**Comment by marcoconti83** [comment]
Hi @MadEgg,
Thanks for clarifying. The description of the scenario you just gave us is enough to identify the bug. It is a known bug that we are currently working on, we will keep you updated on the resolution. 

As for requesting re-transmission, we expect this kind of error ("a message was not received") never to be seen from the user: it should be gone once the bug is fixed. Bear with us for the moment. The only expected case in which a user should get that error is in case of an attack (e.g. man-in-the-middle) and in this case there is no point in requesting the other side to resend the message. Requesting a resend might actually lower the security of the protocol: it would give an attacker some feedback on whether the message they crafted is decoded successfully.

**Comment by MadEgg** [comment]
Great, thanks! I'm looking forward to the solution, keep up the good work!
