### ISSUE TITLE
Better optical distinction of 1:1 and group chats in conversation overview

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#430]
When having a lot of conversations, it's hard to find a specific one in the conversations overview. A clear distinction between 1:1 and group chats would help.

**Comment by MathiasGmeiner** [comment]
I second that! Right now it's really easy to get lost in that list.
Maybe displaying the profile picture would be help to distinguish the conversations.

**Comment by jenskasemets** [comment]
Differentiation between conversation types is now in release 2.34

**Comment by abjbhat** [comment]
There should be better visual distinction of between the chat "bubbles". I find it hard to distinguish between messages between other recipients. This problem is more acute in a group conversation. I would strongly urge the designers to consider a colour scheme for chat "bubbles" from other users, with the option to let the user customise the colours for different participants. 

WhatsApp and Signal get this right.
