### ISSUE TITLE
GIF recognition when sending as file

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#432]
GIFs that are sent from file system on iOS (e.g. from iCloud drive) should automatically be recognised as GIF, so that they are displayed directly in a chat.

**Comment by jenskasemets** [comment]
Hi herrpoerner, 

This behaviour is actually by design. When sending any image, Wire does compress them to reduce bandwidth usage and to speed up user experience.
When sending images through file transfer there's no compression applied to the file, to give an opportunity to send original files when needed.
