### ISSUE TITLE
Notifications for incoming files, pictures and voice messages should be delayed until they're actually downloaded

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#445]
Would be a nice qol change to have the notifications delayed until the picture/voice message/file has actually been completely downloaded. It's a bit unfortunate currently, to see a notification about a new voice message, opening the app and then having to wait all the time until it's actually been downloaded.

This is a suggestion for all platforms, since it doesn't seem to be an ios only "problem" the web version definitely does the same thing.

**Comment by jenskasemets** [comment]
Hi @rbieb , thank you for your input, it's really appreciated.

Current behaviour what you describe, is actually like that by design. All assets, except inline images, are downloaded to the device on user's action. There are several reasons why we have taken such approach. 
— User might have multiple devices and user might have already downloaded received asset on another device, then it's not likely it is needed on other devices. 
— This can cause unwanted data bandwidth usage and battery drainage. For an example, if someone sends you multiple files and you are using mobile network on the go. 
— Filling valuable disk space on mobile device with unnecessary and viewed/consumed assets.

On iOS currently we don't have an option to disable automatic image downloading when using mobile network, this is for sure one thing that we plan to improve in the future.
