### ISSUE TITLE
Screen Lock not asking for TouchID when Wire is started

### ISSUE THREAD

**Issue by Linus9000** [wireapp/wire-ios#758]
Wire asks for TouchID when the app is sent to background, but not when it is started. iPhone 6S, iOS 10.2.1

To reproduce: Configure to ask for TouchID, then kill the app. Now start it again.

**Comment by mikeger** [comment]
Hey @Linus9000 ! Thanks for the reporting. The app lock has a grace period of 10 seconds, which works in both cases if you restart the app or just send it to the background. Try to kill the app and wait 10s, then the lock should appear. If this is not the case, then please ping us here since we would need some more information about the issue.

**Comment by Linus9000** [comment]
Yes, after the delay the lock appears. Which is okay, just a bit unexpected considering similar apps like Threema and Telegram are locked on every start, which led to me thinking this is a bug :) 

Thanks for the prompt clarification, feel free to close this issue if you do not intend to change this.

**Comment by mikeger** [comment]
@Linus9000 no worries, we changed it in the way that the setting copy is more descriptive now: https://github.com/wireapp/wire-ios/pull/762
