### ISSUE TITLE
UX improvement: when untrusted device is added, mark all incoming messages as "trusted" / "untrusted"

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-ios#819]
Cross-post: https://github.com/wireapp/wire-desktop/issues/507

**Comment by jenskasemets** [comment]
Hi @anatoli26,

I'm commenting your request on linked issue. What you request, is actually how Wire already works. To clarify, conversations are verified (connections/sessions between clients), not messages. If now someone adds new devices to the conversation, then in the conversation there's a system message about degradation and new device being added to conversation. To see these messages, you have to first verify fingerprints of all devices in that conversation — otherwise conversation can't degrade in the first place.
Read about exact implementation from our security whitepaper:
https://wire.com/resource/Wire%20Security%20Whitepaper/download/

I'm closing this ticket as this is not iOS specific request, please file all general issues to general repository: https://github.com/wireapp/wire/issues

**Comment by anatoli26** [comment]
Hi Jens, I already have some time using Wire, I've tested quite a bit the current way Wire manages trusting devices. Maybe you haven't checked the description in the linked issue for Wire-desktop, it says the following:

> When untrusted device is added, from that moment all incoming messages should be marked as "trusted" / "untrusted" (could be text, color and/or symbol - alternatively only untrusted messages may be marked as such, so this feature could be enabled always without a UX impact -OR- messages may be marked as trusted/untrusted only when there are untrusted devices, and no mark at all when all are trusted) so one can write to the peer something like "Have you added a new device? Reply from some old device" and if a positive reply comes from a previously trusted devices (and this is indicated in the chat as such) then one can safely add the new device as trusted, no need to verify it via some external channel.

So the suggestion of this issue is to mark somehow messages coming from trusted/untrusted devices (when there are both trusted and untrusted ones, this will happen once the warning appears and the user clicks to continue conversation, nobody clicks on not continuing it) so the peers can resolve the trust without recurring to external channels (like calling by phone or via Wire untrusted channel and trusting the voice, using whatsapp, mail, SMS, etc.).

This way you easily solve the fundamental problem of establishing trust when new devices appear.

This is not iOS-only suggestion, but its implementation should be managed on all platforms, so probably it should be re-opened?
